name: Deploy SEISEL to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_05C57E835B174B2DBAFF354FC61E6F3A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C97E38542B79460CB3C533F8DCC466F0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8969C09192B04EBDA115296B64003735 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-autoescalado-grupo5
          slot-name: Production
          package: .
